apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpserver-gw
  namespace: httpserver
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - httpserver.cncamp.io
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      credentialName: httpserver
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpsserver
spec:
  gateways:
    - httpsserver
  hosts:
    - httpsserver.cncamp.io
  http:
    - match:
        - port: 443
      route:
        - destination:
            host: httpserver.securesvc.svc.cluster.local
            port:
              number: 80